### ISSUE TITLE
[Feature Request] 添加方法`bool Logger.Exist(const char[] name)`判断是否存在该名称的Logger

### ISSUE THREAD

**Issue by blueblur0730** [F1F88/sm-ext-log4sp#12]
一些在实际使用中的总结:
1. 用于plugin late load时判断是否已经创建目标logger.
2. 用于告诉其他plugin是否存在此名称的logger.
由于cpp功底不太好所以没有能力pr... 如果能加上这个功能的话会非常感谢的!

顺便还有一些疑问: 如果reload extension, 那先前已经创建的正在运作的logger也会随着消灭吗?

**Comment by F1F88** [comment]
1. 已在 1.5.0 版本中实现类似的方法：`Logger.Get()`
2. 参考 ①
3. 会的，卸载拓展时所有由拓展创建的资源都应该被清理，再次加载后一切都是干净的

**Comment by F1F88** [comment]
感谢提议

下面是更详细的解释

- 判断 Logger 是否已存在

    很抱歉这其实是一个已知的 bug
    
    按设计预期来说，可以通过下面的代码检验名为 name 的 Logger 是否存在

    ```sourcepawn
    Logger CreateLogger(const char[] name)
    {
        Logger log = Logger.Get(name);
        if (log == INVLIAD_HANDLE)
        {
            PrintToServer("名为 %s 的 Logger 不存在，现在可以自己创建它。", name);
            log = Logger.CreateServerConsoleLogger(name);
        }

        PrintToServer("获取到了名为 %s 的 Logger，现在直接返回它。", name);
        return log;
    }
    ```

    但当前版本的 Logger.Get() 方法没有按预期工作。

- extension 的对象管理

    拓展会在加载时会做以下初始化工作：
    
        1. 创建两种 handle 类型（Logger、Sink）

        2. 添加一个控制台指令 （sm log4sp）

        3. 注册一个全局线程池 （用于异步 Logger）
    
    对应的，在卸载时会做以下清理工作：

        1. 清理所有创建的 handle 对象

        2. 删除两种 handle 类型（SourceMod 在这一步应该也会检查是否还存在这两种类型的 handle 对象，然后删除它们）

        3. 移除一个控制台指令（sm log4sp）

        4. 注销一个全局线程池

**Comment by blueblur0730** [comment]
> 感谢提议
> 
> 下面是更详细的解释
> 
> * 判断 Logger 是否已存在
>   很抱歉这其实是一个已知的 bug
>   按设计预期来说，可以通过下面的代码检验名为 name 的 Logger 是否存在
>   ```sourcepawn
>   Logger CreateLogger(const char[] name)
>   {
>       Logger log = Logger.Get(name);
>       if (log == INVLIAD_HANDLE)
>       {
>           PrintToServer("名为 %s 的 Logger 不存在，现在可以自己创建它。", name);
>           log = Logger.CreateServerConsoleLogger(name);
>       }
>   
>       PrintToServer("获取到了名为 %s 的 Logger，现在直接返回它。", name);
>       return log;
>   }
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   但当前版本的 Logger.Get() 方法没有按预期工作。
> * extension 的对象管理
>   拓展会在加载时会做以下初始化工作：
>   ```
>     1. 创建两种 handle 类型（Logger、Sink）
>   
>     2. 添加一个控制台指令 （sm log4sp）
>   
>     3. 注册一个全局线程池 （用于异步 Logger）
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   对应的，在卸载时会做以下清理工作：
>   ```
>     1. 清理所有创建的 handle 对象
>   
>     2. 删除两种 handle 类型（SourceMod 在这一步应该也会检查是否还存在这两种类型的 handle 对象，然后删除它们）
>   
>     3. 移除一个控制台指令（sm log4sp）
>   
>     4. 注销一个全局线程池
>   ```

感谢如此热心的解释! 希望后续能够用到更完善和更多功能的版本, 十分感谢您的付出!

**Comment by F1F88** [comment]
可以的话欢迎试试刚发布的 v1.5.0-beta

在我的自测中这个问题已经解决，包括其他所有 issue 和已知的 BUG 都已修复。

稳定性上应该也比之前的版本更可靠，因为我对高并发情况进行了多次测试，一切都安然无恙，没有出现服务器崩溃的情况。

但由于这个版本改动非常大，不向下兼容，并且还需要一些时间来更新 wiki 文档，所以目前发布的是预览版。

后续 wiki 文档更新完后，如果没有出现新的问题将再次发布为正式版。

**Comment by blueblur0730** [comment]
> 可以的话欢迎试试刚发布的 v1.5.0-beta
> 
> 在我的自测中这个问题已经解决，包括其他所有 issue 和已知的 BUG 都已修复。
> 
> 稳定性上应该也比之前的版本更可靠，因为我对高并发情况进行了多次测试，一切都安然无恙，没有出现服务器崩溃的情况。
> 
> 但由于这个版本改动非常大，不向下兼容，并且还需要一些时间来更新 wiki 文档，所以目前发布的是预览版。
> 
> 后续 wiki 文档更新完后，如果没有出现新的问题将再次发布为正式版。

好的, 这几天我会抽时间进行测试.
